### ISSUE TITLE
Create Code of Coduct

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/example-node-postgres#11]
**Summary**
Create a code of conduct and add it to the `CODE_OF_CODUCT.MD` file at the folder `.github/` of the project.

**More information**
Code of conduct information, [here](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)
Any questions, just talk :wink:
Happy Hacktoberfest! :smile: 
Let's start? :rocket:

**Comment by klauskpm** [comment]
Hi. I'd like to do it. Can I configure a package to generate a CODE_OF_CONDUCT.MD each time you want?

**Comment by gustafsilva** [comment]
You've created another issue for this. :+1: 
You could do?
