### ISSUE TITLE
Automateing CODE_OF_CODUNTS

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/example-node-postgres#13]
**Summary**
Script creation to automate code of conduct creation :robot: 

**More information**
Create code to automate code of conduct generation :robot: 
As suggested by @klauskpm in #11 :+1: 
Any questions, just talk :wink:
Happy Hacktoberfest! :smile:
Let's start? :rocket:

**Comment by klauskpm** [comment]
Okay. I'll be sending a PR right away o/
