### ISSUE TITLE
Adding rules to contributors

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/example-node-postgres#4]
**Summary**
Create `CONTRIBUTING.md` file with information on how to give a pull request or create an issue in the project and some rules for new contributors. 
You can get a template ready, or add gist with this information.

**More information about file**
The file will be located on the main page of the project.
Because the file does not exist, you can suggest a new format for it.
The file should contain information about how to start a contribution in the project, how to create an issue, and how to propose a change.

Any questions, just talk :wink:
Let's start? :rocket:

**Comment by YuriAbgaryan** [comment]
Can I take this one?

**Comment by gustafsilva** [comment]
Would be great @YuriAbgaryan :+1: 
Any questions, just talk :wink:
