### ISSUE TITLE
Add contributor links in the documentation

### ISSUE THREAD

**Issue by gustafsilva** [gustafsilva/example-node-postgres#6]
**Summary**
Add after `Contribution` information in the `README.md` information about contributors and external links.

Any questions, just talk :wink:
Let's start? :rocket:

**Comment by raul1991** [comment]
I would like to take this up. Can you provide more information about it ?

**Comment by gustafsilva** [comment]
Great @raul1991 :+1: 
Could yes, it would be a section (in the `README.md` file) like the others and that would come on top of the `LICENSE` section.
It could be called `Contributors`, and below a list with the names (can be a photo too) and the GitHub link of each person who contributed to the project.

**Comment by raul1991** [comment]
I am on it. Thanks for the update.
